language: go

branches:
  only:
    - master

matrix:
  include:
    - go: 1.6.x
    - go: 1.7.x
    - go: 1.8.x
    - go: 1.9.x
    - go: tip

install:
 - go get golang.org/x/tools/cmd/cover
 - go get github.com/mattn/goveralls

script:
 - go test -v ./... -covermode=count -coverprofile=coverage.out 
 - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
